version: 16
port: 5432

default_database:
  user: postgres
  password: password

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

replicaCount: 1

services:
  bonusdb:
    name: bonusdb
    container: cr.yandex/crpn5pvljgfvojro6cs1/bonusdb
    replicaCount: 1
    hostPort: 5432
  flightdb:
    name: flightdb
    container: cr.yandex/crpn5pvljgfvojro6cs1/flightdb
    replicaCount: 1
    hostPort: 5433
  ticketdb:
    name: ticketdb
    container: cr.yandex/crpn5pvljgfvojro6cs1/ticketdb
    replicaCount: 1
    hostPort: 5434
